[profile.default]
src = "src"
out = "out"
libs = ["lib"]
#via-ir = true
#optimize = true
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]

[fuzz]
runs = 1000
